version: '3.8'
services:

  app:
    build:
      context: ./src
      dockerfile: Dockerfile.dev
    tty: true
    container_name: python_app
    ports:
      - 1000:8000
    volumes:
      - ./src:/app
    env_file:
      - ./src/.env
