FROM python:3.9-alpine3.16
WORKDIR /app

COPY . .
# COPY ./requirements.txt ./requirements.txt
RUN pip install --no-cache-dir --upgrade -r requirements.txt

CMD ["gunicorn", "-k", "uvicorn.workers.UvicornWorker", "-c", "./gunicorn_config.py", "--reload", "app.main:app"]